[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "zero-sum-sequences"
version = "0.1.0"
description = "Computations with additive and zero-sum sequences"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "Benjamin Hackl" },
]
dependencies = [
  "networkx>=3.2",
]

[project.urls]
Repository = "https://github.com/behackl/zero-sum-sequences"

[project.optional-dependencies]
dev = [
  "pytest>=8.3",
]
sage = [
  "sagelite[gap]==10.9.post1",
]
tutorial = [
  "ipykernel>=6.29",
  "matplotlib>=3.8",
  "nbconvert>=7.16",
]

[tool.hatch.build.targets.wheel]
packages = ["src/zero_sum_sequences"]

[tool.hatch.build.targets.sdist]
include = [
  "/benchmarks",
  "/notebooks/tutorial.ipynb",
  "/src/zero_sum_sequences",
  "/tests",
  "/LICENSE",
  "/README.md",
  "/pyproject.toml",
]

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
pythonpath = ["src"]
